name: UltraRoyales
version: ${version}
main: dev.zxdzero.UltraRoyales.UltraRoyales
bootstrap: dev.zxdzero.UltraRoyales.UltraRoyalesBootstrap
api-version: '1.21'
authors: [ Puzzle_Dude98, Fractial ]
depend: [ZxdzeroEvents]
commands:
  arrowaura:
    description: cool
    permission: ultraroyales.command.arrowaura
  bingoreset:
    description: resets number of bingo attempts
    permission: ultraroyales.command.bingoreset
  withdrawheart:
    description: turns one of your player hearts into a physical item
    permission: ultraroyales.command.withdrawheart
  scenario:
    description: Manage pedestals
    usage: /pedestal <start|end> [scenario]
    permission: ultraroyales.command.scenario
  pod:
    description: gives pod wand
    permission: ultraroyales.command.pod